triggers:
- description: null
  envs: []
  last_enabled_at: 2024-08-10 09:05:26.867680
  name: trigger_training
  pipeline_uuid: train_sklearn
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-08-10 09:05:00
  status: active
  token: 73dd5fc8d6c84d9aa9d714fa408b2850
  variables: {}
